# Generated by Django 2.2.7 on 2019-11-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
