# Generated by Django 2.2.7 on 2019-11-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0002_auto_20191126_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='status_corte',
        ),
    ]
