# Generated by Django 2.2.7 on 2019-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0003_remove_videos_status_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='status',
            field=models.CharField(default='Pendente', max_length=100),
            preserve_default=False,
        ),
    ]
