# Generated by Django 2.2.7 on 2019-11-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0004_videos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
