# Generated by Django 2.2.7 on 2019-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0005_auto_20191126_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=100, null=True),
        ),
    ]
