# Generated by Django 2.2.7 on 2019-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0006_auto_20191126_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
