# Generated by Django 2.2.7 on 2019-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corteapp', '0007_videos_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
