# Generated by Django 2.2.7 on 2019-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acmeplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
                ('nome_arquivo', models.CharField(max_length=100)),
            ],
        ),
    ]
