# Generated by Django 2.2.7 on 2019-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeplayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeplay',
            name='nome_arquivo',
            field=models.CharField(max_length=200),
        ),
    ]
